<a href="https://colab.research.google.com/github/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/blob/main/Use_RandomForest_Pickle_in_Colab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
import pickle
import numpy as np

In [3]:
!ls

sample_data


In [5]:
!wget https://github.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/raw/main/RandomForest.pickle

--2021-07-20 06:35:07--  https://github.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/raw/main/RandomForest.pickle
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/main/RandomForest.pickle [following]
--2021-07-20 06:35:07--  https://raw.githubusercontent.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/main/RandomForest.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 3636099 (3.5M) [application/octet-stream]
Saving to: ‘RandomForest.pickle’

RandomForest.pickle 100%[================

In [6]:
!ls

RandomForest.pickle  sample_data


In [7]:
!wget https://github.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/raw/main/scaller.pickle

--2021-07-20 06:35:48--  https://github.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/raw/main/scaller.pickle
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/main/scaller.pickle [following]
--2021-07-20 06:35:48--  https://raw.githubusercontent.com/islam-mirajul/Rainfall-Prediction-in-Bangladesh-Model-Deployment/main/scaller.pickle
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 642 [application/octet-stream]
Saving to: ‘scaller.pickle’

scaller.pickle      100%[===================>]     642  --.-KB/s    in 0

In [8]:
!ls

RandomForest.pickle  sample_data  scaller.pickle


Make Prediction In colab


In [10]:

Use_classifier = pickle.load(open('RandomForest.pickle','rb'))
Use_scaler = pickle.load(open('scaller.pickle','rb'))

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator DecisionTreeClassifier from version 0.24.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator RandomForestClassifier from version 0.24.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/base.py:318: UserWarning: Trying to unpickle estimator StandardScaler from version 0.24.1 when using version 0.22.2.post1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)


In [11]:
prediction_1 = Use_classifier.predict(Use_scaler.transform(np.array([[13,2.5,2,75,60,5.7,4.8,300]])))

In [12]:
prediction_1

array([0])

In [13]:
prediction_1_proba = Use_classifier.predict_proba(Use_scaler.transform(np.array([[13,2.5,2,75,60,5.7,4.8,300]])))[:,1]

In [14]:
prediction_1_proba

array([0.18])

In [15]:
prediction_2 = Use_classifier.predict(Use_scaler.transform(np.array([[27,26,1,90,94,4.6,5.6,275]])))


In [16]:
prediction_2

array([1])

In [17]:
prediction_2_proba = Use_classifier.predict_proba(Use_scaler.transform(np.array([[27,26,1,90,94,4.6,5.6,275]])))[:,1]

In [18]:
prediction_2_proba

array([0.61])